=== wunderbon/json-schemas/schema/location/location.schema.json
{
  "$id": "https://bitbucket.org/wunderbon/json-schemas/raw/master/schema/location/location.schema.json",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "version": "0.0.1",
  "contact": {
    "name": "wunderbon support",
    "url": "https://wunderbon.io/support",
    "email": "api-support@wunderbon.io"
  },
  "title": "Location",
  "description": "Location representation within the wunderbon domain.",
  "type": "object",
  "properties": {
    "name": {
      "type": "object",
      "oneOf": [
        {
          "$ref": "https://bitbucket.org/wunderbon/json-schemas/raw/master/schema/name/legal/name.schema.json"
        },
        {
          "$ref": "https://bitbucket.org/wunderbon/json-schemas/raw/master/schema/name/private/name.schema.json"
        }
      ]
    },
    "address": {
      "$ref": "https://bitbucket.org/wunderbon/json-schemas/raw/master/schema/address/address.schema.json"
    },
    "communication": {
      "$ref": "https://bitbucket.org/wunderbon/json-schemas/raw/master/schema/communication/communication.schema.json"
    },
    "taxId": {
      "type": "string",
      "oneOf": [
        {
          "$ref": "https://bitbucket.org/wunderbon/json-schemas/raw/master/schema/tax/id/eu/id.schema.json"
        }
      ]
    },
    "serviceTime": {
      "type": "array",
      "items": [
        {
          "$ref": "https://bitbucket.org/wunderbon/json-schemas/raw/master/schema/serviceTime/serviceTime.schema.json"
        }
      ],
      "minItems": 1,
      "maxItems": 7,
      "uniqueItems": true
    },
    "posData": {
      "$ref": "https://bitbucket.org/wunderbon/json-schemas/raw/master/schema/posData/posData.schema.json"
    }
  },
  "additionalProperties": false,
  "required": [
    "address",
    "serviceTime",
    "posData"
  ]
}

=== wunderbon/json-schemas/data/location/location.json
{
  "name": {
    "entityName": "Supermarket GmbH",
    "displayName": "SUPERMarket"
  },
  "address": {
    "name": {
      "entityName": "Supermarket Germany GmbH",
      "displayName": "SUPERMarket DE"
    },
    "street": {
      "name": "Burgstraße",
      "number": 37
    },
    "zip": "45476",
    "city": "Mülheim an der Ruhr",
    "country": "DE",
    "gps": {
      "latitude": 51.441050,
      "longitude": 6.861170
    }
  },
  "communication": {
    "phone": [
      {
        "areaCode": {
          "country": "49",
          "local": "211"
        },
        "number": "123456",
        "name": "Customer Care"
      }
    ]
  },
  "taxId": "DE127135609",
  "posData": {
    "count": 5
  },
  "serviceTime": [
    {
      "weekday": "Monday",
      "from": {
        "hour": 8,
        "minute": 0
      },
      "to": {
        "hour": 20,
        "minute": 0
      }
    }
  ]
}
