=== wunderbon/json-schemas/schema/receipt/receipt.schema.json
{
  "$id": "https://bitbucket.org/wunderbon/json-schemas/raw/master/schema/receipt/receipt.schema.json",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "version": "v0.3.2",
  "contact": {
    "name": "wunderbon International B.V.",
    "url": "https://developers.wunderbon.io",
    "email": "open-source@wunderbon.io"
  },
  "title": "Receipt",
  "description": "A receipt representation within the wunderbon domain.",
  "type": "object",
  "properties": {
    "merchant": {
      "description": "The Id of the issuer (Merchant). Each Merchant will recive an unique User-Id.",
      "$ref": "https://bitbucket.org/wunderbon/json-schemas/raw/master/schema/uuid/uuid.schema.json"
    },
    "location": {
      "description": "The Id of the location. Each location (branch) of a Merchant has its own Id.",
      "$ref": "https://bitbucket.org/wunderbon/json-schemas/raw/master/schema/uuid/uuid.schema.json"
    },
    "pos": {
      "description": "The Id of the PoS. Each PoS within at the location (branch) has its own Id.",
      "$ref": "https://bitbucket.org/wunderbon/json-schemas/raw/master/schema/uuid/uuid.schema.json"
    },
    "header": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1,
        "maxLength": 42
      },
      "minItems": 0,
      "maxItems": 10
    },
    "cart": {
      "description": "The cart contains a collection of cartItems (representation of a product, merchant added information and the pricing).",
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "https://bitbucket.org/wunderbon/json-schemas/raw/master/schema/cartItem/cartItem.schema.json"
          }
        }
      }
    },
    "payment": {
      "description": "Payment part of the receipt. This node contains information on how the amount of the cart was settled.",
      "type": "object",
      "properties": {
        "amount": {
          "$ref": "https://bitbucket.org/wunderbon/json-schemas/raw/master/schema/amount/amount.schema.json"
        }
      }
    },
    "footer": {
      "description": "Footer lines to be printed on bottom of receipt. Often used to print information about special deals or a new website.",
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1,
        "maxLength": 42
      },
      "minItems": 0,
      "maxItems": 10
    }
  },
  "additionalProperties": false,
  "required": [
    "merchant",
    "location",
    "cart",
    "payment"
  ]
}

=== wunderbon/json-schemas/data/receipt/receipt.json
{
  "header": [
    "***************",
    "*   New Job?  *",
    "* www.job.com *",
    "***************"
  ],
  "merchant": "9a037d60-424a-4669-97de-db219da1c284",
  "location": "de9aab99-c419-42df-9a95-7f13df545295",
  "pos": "6c1ef643-e116-4eb4-abb7-1df23a027898",
  "cart": {
    "items": [
      {
        "product": {

        }
      }
    ]
  },
  "payment": {
    "type": "",
    "amount": {
      "value": 1.99,
      "currency": "EUR"
    }
  },
  "footer": [
    "Thank you for shopping at",
    "your favorite supermarket!",
    "Check our online delivery",
    "online-delivery-supermarket.com"
  ]
}

=== wunderbon/json-schemas/data/receipt/receiptFull.json
{
  "header": [
    "***************",
    "*   New Job?  *",
    "* www.job.com *",
    "***************"
  ],
  "merchant": "9a037d60-424a-4669-97de-db219da1c284",
  "location": "de9aab99-c419-42df-9a95-7f13df545295",
  "pos": "6c1ef643-e116-4eb4-abb7-1df23a027898",
  "cart": {
    "items": [
      {
        "product": {
          "data": {
            "code": "0720260063170"
          },
          "price": {
            "net": {
              "value": 1.85981,
              "currency": "EUR"
            },
            "gross": {
              "value": 1.99,
              "currency": "EUR"
            },
            "tax": {
              "type": "VAT",
              "percentage": 7.00
            }
          },
          "quantifier": {
            "quantity": 1,
            "unit": "pcs"
          }
        },
        "meta": {
          "category": "non-food",
          "position": 1,
          "group": "Drugs",
          "groupPosition": 1
        }
      },
      {
        "product": {
          "data": {
            "code": "0720260063170"
          },
          "price": {
            "net": {
              "value": 1.85981,
              "currency": "EUR"
            },
            "gross": {
              "value": 1.99,
              "currency": "EUR"
            },
            "tax": {
              "type": "VAT",
              "percentage": 7.00
            }
          },
          "quantifier": {
            "quantity": 1,
            "unit": "pcs"
          }
        },
        "meta": {
          "category": "food",
          "position": 2,
          "group": "Food",
          "groupPosition": 1
        }
      }
    ]
  },
  "payment": {
    "type": "",
    "amount": {
      "value": 1.99,
      "currency": "EUR"
    }
  },
  "footer": [
    "Thank you for shopping at",
    "your favorite supermarket!",
    "Check our online delivery",
    "online-delivery-supermarket.com"
  ]
}
