=== wunderbon/json-schemas/schema/communication/communication.schema.json
{
  "$id": "https://bitbucket.org/wunderbon/json-schemas/raw/master/schema/communication/communication.schema.json",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "version": "v0.4.19",
  "contact": {
    "name": "wunderbon Operation GmbH & Co. KG",
    "url": "https://developers.wunderbon.io",
    "email": "open-source@wunderbon.io"
  },
  "title": "Communication",
  "description": "Communication representation within the wunderbon domain.",
  "type": "object",
  "properties": {
    "phone": {
      "description": "Phone number.",
      "type": "array",
      "items": [
        {
          "$ref": "https://bitbucket.org/wunderbon/json-schemas/raw/master/schema/phoneNumber/phoneNumber.schema.json"
        }
      ],
      "minItems": 1,
      "maxItems": 3,
      "uniqueItems": true
    },
    "fax": {
      "description": "Fax number.",
      "type": "array",
      "items": [
        {
          "$ref": "https://bitbucket.org/wunderbon/json-schemas/raw/master/schema/phoneNumber/phoneNumber.schema.json"
        }
      ],
      "minItems": 1,
      "maxItems": 3,
      "uniqueItems": true
    },
    "www": {
      "description": "Internet address.",
      "type": "string",
      "pattern": "(https?)://(-\\.)?([^\\s/?\\.#-]+\\.?)+(/[^\\s]*)?$",
      "maxLength": 1024,
      "examples": [
        "https://www.supermarket-germany.com",
        "https://www.example.com"
      ]
    },
    "email": {
      "description": "Email address.",
      "$ref": "https://bitbucket.org/wunderbon/json-schemas/raw/master/schema/email/email.schema.json"
    }
  },
  "additionalProperties": false
}

=== wunderbon/json-schemas/data/communication/communication.json
{
  "phone": [
    {
      "areaCode": {
        "country": "49",
        "local": "23235"
      },
      "number": "2323235"
    },
    {
      "areaCode": {
        "country": "49",
        "local": "23235"
      },
      "number": "5232323"
    }
  ],
  "fax": [
    {
      "areaCode": {
        "country": "49",
        "local": "23235"
      },
      "number": "2323236"
    },
    {
      "areaCode": {
        "country": "49",
        "local": "23235"
      },
      "number": "6232323"
    }
  ],
  "email": "foo@bar.com",
  "www": "https://www.google.com/"
}
