=== wunderbon/json-schemas/schema/assistance/assistance.schema.json
{
  "$id": "https://bitbucket.org/wunderbon/json-schemas/raw/master/schema/assistance/assistance.schema.json",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "version": "v0.1.0",
  "contact": {
    "name": "wunderbon Operation GmbH & Co. KG",
    "url": "https://developers.wunderbon.io",
    "email": "open-source@wunderbon.io"
  },
  "title": "Assistance",
  "description": "Assistance representation within the wunderbon domain.",
  "type": "object",
  "properties": {
    "locale": {
      "description": "Valid locale: Language and territory are represented by two- or three-character ISO-639 or two-character ISO-3166 codes (e.g. de-DE for German/Germany, de-AT for German/Austria or gsw-CH for Swiss German/Switzerland).",
      "$ref": "https://bitbucket.org/wunderbon/json-schemas/raw/master/schema/locale/locale.schema.json"
    },
    "device": {
      "description": "Device on which the assistance is available. Will become a matrix with medium.",
      "type": "string",
      "enum": [
        "smartphone",
        "tablet",
        "computer"
      ],
      "examples": [
        "smartphone"
      ]
    },
    "medium": {
      "description": "Medium on which the assistance is available. Will become a matrix with device.",
      "type": "string",
      "enum": [
        "app",
        "web-app"
      ],
      "examples": [
        "app"
      ]
    },
    "entity": {
      "description": "Id of the entity the assistance belongs to.",
      "$ref": "https://bitbucket.org/wunderbon/json-schemas/raw/master/schema/uuid/uuid.schema.json"
    },
    "hint": {
      "description": "Hint shown for further assistance.",
      "type": "string",
      "maxLength": 512,
      "examples": [
        "Hi and welcome to our Foo-Screen. Here you can manage your foo, bar and your baz as well."
      ]
    }
  },
  "additionalProperties": false,
  "required": [
    "entity",
    "hint",
    "locale"
  ]
}

=== wunderbon/json-schemas/data/assistance/assistance.json
{
  "device": "smartphone",
  "medium": "app",
  "entity": "71ad569b-b248-47ab-a468-952f3dac3dd2",
  "hint": "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.",
  "locale": "de-DE"
}
