=== wunderbon/json-schemas/schema/tse/tse.schema.json
{
  "$id": "https://bitbucket.org/wunderbon/json-schemas/raw/master/schema/tse/tse.schema.json",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "version": "v0.1.0",
  "contact": {
    "name": "wunderbon Operation GmbH & Co. KG",
    "url": "https://developers.wunderbon.io",
    "email": "open-source@wunderbon.io"
  },
  "title": "TSE",
  "description": "A TSE (https://kassensichv.net/technische-sicherheitseinrichtung/) representation within the wunderbon domain.",
  "type": "object",
  "properties": {
    "signature": {
      "description": "The TSE signature.",
      "type": "string",
      "maxLength": 512,
      "examples": [
        "kMgncWoSSGY0je/b4WhW3WupFo4N83skfvT4kDm2uZigSlSzCfh0NT3tgRR2n5VAEhxxfJxQEhv/LA9VmwOirw6lzwYR7Ori4lr2+dj4Ox3L2aj8VytF13OvuY7dTonQ"
      ]
    },
    "transactionCount": {
      "description": "The TSE transaction counter.",
      "type": "number",
      "minimum": 1,
      "examples": [
        11846
      ]
    },
    "start": {
      "description": "The TSE start timestamp.",
      "type": "string",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}.\\d{3}Z$",
      "maxLength": 24,
      "examples": [
        "2021-02-10T15:40:08.000Z"
      ]
    },
    "end": {
      "description": "The TSE end timestamp.",
      "type": "string",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}.\\d{3}Z$",
      "maxLength": 24,
      "examples": [
        "2021-02-10T15:40:44.000Z"
      ]
    },
    "timezone": {
      "type": "string",
      "description": "The timezone of start and stop.",
      "enum": [
        "UTC"
      ],
      "examples": [
        "UTC"
      ]
    },
    "serialNumber": {
      "description": "The serial number or unique identifier of the POS.",
      "type": "string",
      "minLength": 1,
      "maxLength": 255
    },
    "signatureCount": {
      "description": "The TSE transaction counter.",
      "type": "number",
      "minimum": 1,
      "examples": [
        23685
      ]
    },
    "algorithm": {
      "description": "The algorithm used for calculating the signature.",
      "type": "string",
      "maxLength": 512,
      "examples": [
        "ecdsa-plain-SHA256"
      ]
    },
    "publicKey": {
      "description": "Public key of TSE signature.",
      "type": "string",
      "minLength": 128,
      "maxLength": 128,
      "examples": [
        "MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMHRCTwqWUvX3M7ip7b0pmh5Rs5FsiQju+00maOXAlY6zQRVr7Qa3nrGtQHWTxeC7tyPTeH1mmduWiG+VFtV/ucCAwEAAQ=="
      ]
    },
    "barcode": {
      "description": "QR-Code representing the data of TSE.",
      "$ref": "https://bitbucket.org/wunderbon/json-schemas/raw/master/schema/barcode/barcode.schema.json"
    }
  },
  "required": [
    "signature",
    "transactionCount",
    "start",
    "end",
    "serialNumber",
    "signatureCount"
  ],
  "additionalProperties": false
}

=== wunderbon/json-schemas/data/tse/tse.json
{
  "signature": "kMgncWoSSGY0je/b4WhW3WupFo4N83skfvT4kDm2uZigSlSzCfh0NT3tgRR2n5VAEhxxfJxQEhv/LA9VmwOirw6lzwYR7Ori4lr2+dj4Ox3L2aj8VytF13OvuY7dTonQ",
  "transactionCount": 11846,
  "start": "2021-02-10T15:40:08.000Z",
  "end": "2021-02-10T15:40:43.000Z",
  "serialNumber": "EXAMPLE:00:01:2e:42:62:3a:00",
  "signatureCount": 23685,
  "barcode": {
    "format": "QR-Text",
    "data": "V0;es-9999999999-0001-53;Kassenbeleg-V1;Beleg^22.50_5.95_0.00_0.00_0.00^30.00:Bar:EUR;58;117;2020-01-16T13:31:29.578+01;2020-01-16T13:31:45.547+01;SHA384WITHECDSA;Utc;Sa8QLLmxPXyL4xxgnI6y8clsKLL0xbk8aeiD2t5WWFD07JJU76S5Lol6PTgr6HCSD7pzEOx75WgDOHzuYF6uV2lBmh3Xvu1eou6cjtp+rLYwMO4XYR9/7cH0M/YyPUJj;MHowFAYHKoZIzj0CAQYJKyQDAwIIAQELA2IABASOg+EOCUQ4Qt0CSWj2xrXoRodCQOJgZfh8paJvV4USOGmr6HBIq4gL/WJRrUFqQS920bw0eGYTo0XEQPKV09sg2JL3hmg0emfFTpl0LEOhm2OYsfgvl6VPkY9wvZ+lLQ=="
  }
}
