=== wunderbon/json-schemas/schema/merchant.schema.json
{
  "$id": "https://bitbucket.org/wunderbon/json-schemas/raw/master/schema/merchant.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Merchant",
  "description": "Merchant representation within the wunderbon domain.",
  "type": "object",
  "properties": {
    "name": {
      "oneOf": [
        {
          "$ref": "name/legal/name.schema.json"
        },
        {
          "$ref": "name/private/name.schema.json"
        }
      ]
    },
    "address": {
      "$ref": "address/address.schema.json"
    },
    "communication": {
      "$ref": "communication/communication.schema.json"
    },
    "taxId": {
      "type": "string",
      "minLength": 3,
      "maxLength": 255,
      "pattern": "^((AT)?U[0-9]{8}|(BE)?0[0-9]{9}|(BG)?[0-9]{9,10}|(CY)?[0-9]{8}L|(CZ)?[0-9]{8,10}|(DE)?[0-9]{9}|(DK)?[0-9]{8}|(EE)?[0-9]{9}|(EL|GR)?[0-9]{9}|(ES)?[0-9A-Z][0-9]{7}[0-9A-Z]|(FI)?[0-9]{8}|(FR)?[0-9A-Z]{2}[0-9]{9}|(GB)?([0-9]{9}([0-9]{3})?|[A-Z]{2}[0-9]{3})|(HU)?[0-9]{8}|(IE)?[0-9]S[0-9]{5}L|(IT)?[0-9]{11}|(LT)?([0-9]{9}|[0-9]{12})|(LU)?[0-9]{8}|(LV)?[0-9]{11}|(MT)?[0-9]{8}|(NL)?[0-9]{9}B[0-9]{2}|(PL)?[0-9]{10}|(PT)?[0-9]{9}|(RO)?[0-9]{2,10}|(SE)?[0-9]{12}|(SI)?[0-9]{8}|(SK)?[0-9]{10})$"
    }
  },
  "additionalProperties": false,
  "required": [
    "name",
    "address",
    "communication",
    "taxId"
  ]
}

=== wunderbon/json-schemas/data/merchant/merchant.json
{
  "name": {
    "entityName": "Aldi Einkauf GmbH & Co. oHG Süd",
    "displayName": "ALDI Süd"
  },
  "address": {
    "name": {
      "$ref":  "#/name/displayName"
    },
    "street": {
      "name": "Burgstraße",
      "number": 37
    },
    "zip": "45476",
    "city": "Mülheim an der Ruhr",
    "country": "DE",
    "gps": {
      "latitude": 51.441050,
      "longitude": 6.861170
    }
  },
  "communication": {

  },
  "taxId": "DE127135609"
}
