=== wunderbon/json-schemas/schema/terminal/terminalStructured.schema.json
{
  "$id": "https://bitbucket.org/wunderbon/json-schemas/raw/master/schema/terminal/terminalStructured.schema.json",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "version": "v0.1.0",
  "contact": {
    "name": "wunderbon Operation GmbH & Co. KG",
    "url": "https://developers.wunderbon.io",
    "email": "open-source@wunderbon.io"
  },
  "title": "Terminal-Structured",
  "description": "A structured terminal response representation within the wunderbon domain.",
  "type": "object",
  "properties": {
    "title": {
      "description": "The title of the sales slip.",
      "type": "string",
      "minLength": 1,
      "maxLength": 50,
      "examples": [
        "+ K U N D E N B E L E G +",
        "-K-U-N-D-E-N-B-E-L-E-G-",
        "- C U S T O M E R -"
      ]
    },
    "date": {
      "description": "Date of the transaction (ISO 8601 YYYY-MM-TT).",
      "type": "string",
      "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$",
      "examples": [
        "2020-01-01",
        "2020-03-05",
        "2019-05-23"
      ]
    },
    "time": {
      "description": "Time of the transaction (e.g. 12:00:00).",
      "type": "string",
      "pattern": "^[0-9]{2}:[0-9]{2}:[0-9]{2}$",
      "examples": [
        "12:00:00",
        "23:39:00"
      ]
    },
    "receiptNumber": {
      "description": "The number of the receipt.",
      "type": "string",
      "minLength": 1,
      "maxLength": 12,
      "examples": [
        "65391584",
        "61481409"
      ]
    },
    "transactionNumber": {
      "description": "The number of the transaction.",
      "type": "string",
      "minLength": 1,
      "maxLength": 12,
      "examples": [
        "65391584",
        "61481409"
      ]
    },
    "contactless": {
      "description": "Flag for contactless payments.",
      "type": "boolean",
      "default": false
    },
    "cardType": {
      "description": "Type of card used.",
      "type": "string",
      "enum": [
        "Debit Mastercard",
        "Girocard",
        "SEPA-Lastschrift",
        "SEPA ELV",
        "EuroELV"
      ]
    },
    "truncatedPan": {
      "description": "The PAN of the card used for transaction (https://de.wikipedia.org/wiki/ISO/IEC_7810#Track_#_2).",
      "$ref": "https://bitbucket.org/wunderbon/json-schemas/raw/master/schema/truncatedNumber/truncatedNumber.schema.json"
    },
    "cardSequenceNumber": {
      "description": "The card sequence number.",
      "type": "string",
      "maxLength": 3,
      "examples": [
        "1",
        "9"
      ]
    },
    "emvApplicationIdentifier": {
      "description": "The EMV-AID of the transaction (https://www.eftlab.com/knowledge-base/211-emv-aid-rid-pix/).",
      "type": "string",
      "maxLength": 128,
      "examples": [
        "A0000003591010028001",
        "A0000000041010"
      ]
    },
    "contractingCompanyNumber": {
      "description": "The VU-Nr. of the transaction (https://www.novalnet.de/payment-lexikon/vu-nummer).",
      "type": "string",
      "maxLength": 128,
      "examples": [
        "132013",
        "0511110006"
      ]
    },
    "terminalId": {
      "description": "The Id of the terminal.",
      "type": "string",
      "minLength": 1,
      "maxLength": 12,
      "examples": [
        "65391584",
        "61481409"
      ]
    },
    "emvDataBuffer": {
      "description": "Additional buffered lines from EMV.",
      "type": "array",
      "items": {
        "anyOf": [
          {
            "description": "A line with max length of characters.",
            "type": "string",
            "minLength": 0,
            "maxLength": 50
          }
        ]
      }
    },
    "total": {
      "description": "Total amount of transaction.",
      "$ref": "https://bitbucket.org/wunderbon/json-schemas/raw/master/schema/amount/amount.schema.json"
    }
  },
  "required": [
    "title",
    "date",
    "time",
    "receiptNumber",
    "transactionNumber",
    "contactless",
    "cardType",
    "truncatedPan",
    "cardSequenceNumber",
    "emvApplicationIdentifier",
    "contractingCompanyNumber",
    "terminalId",
    "emvDataBuffer",
    "total"
  ],
  "additionalProperties": false
}

=== wunderbon/json-schemas/data/terminal/terminalStructured.json
{
  "terminalId": "65110006",
  "receiptNumber": "0371",
  "transactionNumber": "000904",
  "date": "2007-08-31",
  "time": "16:47:00",
  "total": {
    "value": 1.50,
    "currency": "EUR"
  },
  "title": "-K-U-N-D-E-N-B-E-L-E-G-",
  "contractingCompanyNumber": "0511110006",
  "cardType": "Debit Mastercard",
  "contactless": true,
  "truncatedPan": {
    "number": "############0527",
    "asterisks": "#"
  },
  "cardSequenceNumber": "1",
  "emvApplicationIdentifier": "A0000000041010",
  "emvDataBuffer": [
    "0020008001/A800/3F0002//",
    "",
    "00 GENEHMIGUNG KARTE",
    "GEPRUEFT"
  ]
}
