=== wunderbon/json-schemas/schema/cartItem/cartItem.schema.json
{
  "$id": "https://bitbucket.org/wunderbon/json-schemas/raw/master/schema/cartItem/cartItem.schema.json",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "version": "v0.3.2",
  "contact": {
    "name": "wunderbon International B.V.",
    "url": "https://developers.wunderbon.io",
    "email": "open-source@wunderbon.io"
  },
  "title": "Cart-Item",
  "description": "A cart item representation within the wunderbon domain.",
  "type": "object",
  "properties": {
    "uid": {
      "type": "string",
      "description": "Unique Id of the item (e.g. retailers product number).",
      "minLength": 1,
      "maxLength": 255
    },
    "quantifier": {
      "$ref": "https://bitbucket.org/wunderbon/json-schemas/raw/master/schema/cartItem/quantifier/quantifier.schema.json"
    },
    "name": {
      "type": "string",
      "description": "Name of this item.",
      "minLength": 3,
      "maxLength": 255
    },
    "share": {
      "type": "object",
      "description": "Share configuration for sharing item on social networks & others.",
      "properties": {
        "text": {
          "type": "string",
          "description": "Text used when sharing item.",
          "maxLength": 255
        },
        "image": {
          "$ref": "https://bitbucket.org/wunderbon/json-schemas/raw/master/schema/image/image.schema.json"
        }
      },
      "required": [
        "text"
      ]
    },
    "rating": {
      "type": "object",
      "description": "Rating of item.",
      "properties": {
        "votes": {
          "type": "integer",
          "description": "Count of votes."
        },
        "sum": {
          "type": "number",
          "description": "Sum of single ratings."
        }
      },
      "required": [
        "votes",
        "sum"
      ]
    },
    "description": {
      "type": "string",
      "description": "Description of this item.",
      "minLength": 3,
      "maxLength": 1024
    },
    "ean13": {
      "type": "string",
      "description": "EAN13 code of this item.",
      "pattern": "^[0-9]{13}$",
      "minLength": 13,
      "maxLength": 13
    },
    "pricing": {
      "$ref": "https://bitbucket.org/wunderbon/json-schemas/raw/master/schema/cartItem/pricing/pricing.schema.json"
    }
  },
  "additionalProperties": false
}

=== wunderbon/json-schemas/data/cartItem/cartItem.json
{
  "uid": "12345",
  "name": "Babybel Scheiben 100g",
  "description": "Babybel Scheiben 50% Fett i.Tr.100g\nLaktosefrei\nohne Zusatz von Konservierungsstoffen\nreif\nUnter Schutzatmosph√§re verpackt",
  "ean13": "3073780855358",
  "quantifier": {
    "quantity": 1,
    "unit": "pcs"
  },
  "pricing": {
    "net": 1.85981,
    "gross": 1.99,
    "tax": {
      "type": "VAT",
      "percentage": 7.00
    }
  }
}
